site_name: Dicas de Django
site_description: Algumas dicas úteis de Django e Django Rest
site_url: https://github.com/DarknessRdg/django-rest-tutorial
edit_uri: docs/

site_author: https://darknessrdg.github.io/

site_dir: ../docs/

# Page tree
nav:
  - Home: index.md
  - Django:
    - Configurar ambiente django para usar imagens: imagem.md
    - Mover django model de um app para outro: move_model_to_another.md
  - DRF:
    - UrlField com vários lookups: url_field_many_lookups.md
    - Extra asserts para API testes: api_asserts.md

# Repository
repo_name: DarknessRdg/django-rest-tutorial
repo_url: https://github.com/DarknessRdg/django-rest-tutorial

# Configuration
theme:
  name: material
  favicon: img/favicon.ico
  palette:
    primary: indigo
    accent: light blue
  icon:
    logo: fontawesome/solid/code
  features:
    - instant

# Customization
extra:
  social:
    - icon: fontawesome/solid/user
      link: https://darknessrdg.github.io/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/DarknessRdg
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/luan_26/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/luan.dasilva.925

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
